name: climora
description: Flutter weather app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  dio_smart_retry: ^7.0.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.0
  geolocator: ^13.0.1
  get_it: ^8.0.3
  intl: ^0.20.2
  lottie: ^3.3.1
  number_paginator: ^1.1.1
  path: ^1.9.1
  shared_preferences: ^2.3.4
  sqflite: ^2.4.2

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
  - assets/lottie/
